permalink: /:year/:month/:day/:title.html
paginate: 10
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions:
    - fenced_code_blocks
    - no_intra_emphasis
    - strikethrough
    - autolink
    - tables

# 作者信息
author: 
  name: mZero
  email: xmbupt@gmail.com
  link: http://example.com
  weibo: http://example.com
  github: http://example.com
  music: http://example.com
  linkedin: http://example.com

# 站点信息
title: mZero
description: keep moving
url: http://painterlin.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/tekk.jpg
favicon: /public/img/tekk.jpg

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: painterlin.com

# disqus 设置
disqus:
  shortname: mZero

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - 技术


# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档